import type {
  User,
  Lead,
  Project,
  Task,
  Reward,
  Activity,
  PointEvent,
} from './types'

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@noon.app',
    name: 'Carlos Admin',
    role: 'admin',
    avatar: '',
    createdAt: new Date('2024-01-01'),
    points: 5000,
    balance: 15000,
  },
  {
    id: '2',
    email: 'maria@noon.app',
    name: 'Maria Gonzalez',
    role: 'sales_manager',
    avatar: '',
    createdAt: new Date('2024-01-15'),
    points: 3500,
    balance: 8500,
  },
  {
    id: '3',
    email: 'juan@noon.app',
    name: 'Juan Perez',
    role: 'sales',
    avatar: '',
    createdAt: new Date('2024-02-01'),
    points: 2200,
    balance: 4200,
  },
  {
    id: '4',
    email: 'ana@noon.app',
    name: 'Ana Rodriguez',
    role: 'pm',
    avatar: '',
    createdAt: new Date('2024-02-15'),
    points: 1800,
    balance: 6000,
  },
  {
    id: '5',
    email: 'pedro@noon.app',
    name: 'Pedro Martinez',
    role: 'developer',
    avatar: '',
    createdAt: new Date('2024-03-01'),
    points: 1500,
    balance: 3500,
  },
  {
    id: '6',
    email: 'laura@noon.app',
    name: 'Laura Sanchez',
    role: 'developer',
    avatar: '',
    createdAt: new Date('2024-03-15'),
    points: 1200,
    balance: 2800,
  },
]

// Mock Leads
export const mockLeads: Lead[] = [
  {
    id: 'l1',
    name: 'Roberto Diaz',
    email: 'roberto@techcorp.com',
    phone: '+52 55 1234 5678',
    company: 'TechCorp Solutions',
    source: 'website',
    status: 'new',
    score: 85,
    value: 25000,
    assignedTo: '3',
    assignmentStatus: 'owned',
    notes: 'Interesado en desarrollo de app movil',
    tags: ['mobile', 'high-value', 'tech'],
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'l2',
    name: 'Sofia Herrera',
    email: 'sofia@retailplus.mx',
    phone: '+52 33 9876 5432',
    company: 'Retail Plus',
    source: 'referral',
    status: 'contacted',
    score: 72,
    value: 18000,
    assignedTo: '3',
    assignmentStatus: 'owned',
    notes: 'Necesita e-commerce con integracion ERP',
    tags: ['ecommerce', 'integration'],
    createdAt: new Date('2024-11-28'),
    updatedAt: new Date('2024-12-02'),
    lastContactedAt: new Date('2024-12-02'),
  },
  {
    id: 'l3',
    name: 'Miguel Torres',
    email: 'miguel@financegroup.com',
    company: 'Finance Group MX',
    source: 'cold_call',
    status: 'qualified',
    score: 91,
    value: 45000,
    assignedTo: '3',
    assignmentStatus: 'owned',
    notes: 'Dashboard financiero con reportes automaticos',
    tags: ['fintech', 'dashboard', 'enterprise'],
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-12-03'),
    lastContactedAt: new Date('2024-12-03'),
  },
  {
    id: 'l4',
    name: 'Carmen Vega',
    email: 'carmen@healthtech.io',
    phone: '+52 81 5555 1234',
    company: 'HealthTech IO',
    source: 'event',
    status: 'proposal',
    score: 88,
    value: 35000,
    assignedTo: '3',
    assignmentStatus: 'owned',
    notes: 'Plataforma de telemedicina',
    tags: ['health', 'platform', 'saas'],
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-12-04'),
    lastContactedAt: new Date('2024-12-04'),
  },
  {
    id: 'l5',
    name: 'Fernando Luna',
    email: 'fernando@logistica360.mx',
    company: 'Logistica 360',
    source: 'website',
    status: 'negotiation',
    score: 78,
    value: 22000,
    assignedTo: '3',
    assignmentStatus: 'owned',
    notes: 'Sistema de tracking de envios',
    tags: ['logistics', 'tracking', 'mobile'],
    createdAt: new Date('2024-11-10'),
    updatedAt: new Date('2024-12-05'),
    lastContactedAt: new Date('2024-12-05'),
  },
  {
    id: 'l6',
    name: 'Isabella Mendez',
    email: 'isabella@edulearn.com',
    company: 'EduLearn',
    source: 'social',
    status: 'won',
    score: 95,
    value: 55000,
    assignedTo: '3',
    assignmentStatus: 'owned',
    notes: 'LMS completo con gamificacion',
    tags: ['education', 'lms', 'enterprise'],
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-11-30'),
    lastContactedAt: new Date('2024-11-30'),
  },
  {
    id: 'l7',
    name: 'Alejandro Rios',
    email: 'alejandro@startupx.io',
    company: 'StartupX',
    source: 'referral',
    status: 'lost',
    score: 45,
    value: 12000,
    assignedTo: '3',
    assignmentStatus: 'owned',
    notes: 'MVP para startup - perdido por presupuesto',
    tags: ['startup', 'mvp'],
    createdAt: new Date('2024-10-15'),
    updatedAt: new Date('2024-11-20'),
    lastContactedAt: new Date('2024-11-20'),
  },
]

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: 'p1',
    name: 'EduLearn LMS Platform',
    description: 'Sistema de gestion de aprendizaje con gamificacion',
    clientId: 'c1',
    clientName: 'EduLearn',
    status: 'in_progress',
    budget: 55000,
    startDate: new Date('2024-12-01'),
    endDate: new Date('2025-03-01'),
    pmId: '4',
    pmName: 'Ana Rodriguez',
    teamIds: ['5', '6'],
    createdAt: new Date('2024-11-30'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: 'p2',
    name: 'Finance Dashboard',
    description: 'Dashboard financiero con reportes automaticos',
    clientId: 'c2',
    clientName: 'Finance Group MX',
    status: 'backlog',
    budget: 45000,
    pmId: '4',
    pmName: 'Ana Rodriguez',
    teamIds: [],
    createdAt: new Date('2024-12-03'),
    updatedAt: new Date('2024-12-03'),
  },
  {
    id: 'p3',
    name: 'HealthTech Telemedicina',
    description: 'Plataforma de telemedicina con videollamadas',
    clientId: 'c3',
    clientName: 'HealthTech IO',
    status: 'review',
    budget: 35000,
    startDate: new Date('2024-10-01'),
    endDate: new Date('2024-12-15'),
    pmId: '4',
    pmName: 'Ana Rodriguez',
    teamIds: ['5'],
    createdAt: new Date('2024-09-28'),
    updatedAt: new Date('2024-12-05'),
  },
  {
    id: 'p4',
    name: 'Retail Plus E-commerce',
    description: 'E-commerce con integracion ERP',
    clientId: 'c4',
    clientName: 'Retail Plus',
    status: 'completed',
    budget: 28000,
    startDate: new Date('2024-08-01'),
    endDate: new Date('2024-11-15'),
    pmId: '4',
    pmName: 'Ana Rodriguez',
    teamIds: ['6'],
    createdAt: new Date('2024-07-28'),
    updatedAt: new Date('2024-11-15'),
  },
]

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: 't1',
    projectId: 'p1',
    title: 'Diseño de base de datos',
    description: 'Crear esquema de BD para usuarios, cursos y progreso',
    status: 'done',
    priority: 'high',
    assignedTo: '5',
    assignedToName: 'Pedro Martinez',
    dueDate: new Date('2024-12-10'),
    estimatedHours: 8,
    actualHours: 6,
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-08'),
  },
  {
    id: 't2',
    projectId: 'p1',
    title: 'API de autenticacion',
    description: 'Implementar login, registro y manejo de sesiones',
    status: 'in_progress',
    priority: 'high',
    assignedTo: '5',
    assignedToName: 'Pedro Martinez',
    dueDate: new Date('2024-12-15'),
    estimatedHours: 12,
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-10'),
  },
  {
    id: 't3',
    projectId: 'p1',
    title: 'Dashboard de estudiante',
    description: 'Vista principal con progreso y cursos activos',
    status: 'todo',
    priority: 'medium',
    assignedTo: '6',
    assignedToName: 'Laura Sanchez',
    dueDate: new Date('2024-12-20'),
    estimatedHours: 16,
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 't4',
    projectId: 'p1',
    title: 'Sistema de gamificacion',
    description: 'Puntos, badges y leaderboard',
    status: 'todo',
    priority: 'medium',
    assignedTo: '6',
    assignedToName: 'Laura Sanchez',
    dueDate: new Date('2024-12-28'),
    estimatedHours: 20,
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 't5',
    projectId: 'p3',
    title: 'Integracion videollamadas',
    description: 'Integrar Twilio para consultas virtuales',
    status: 'review',
    priority: 'urgent',
    assignedTo: '5',
    assignedToName: 'Pedro Martinez',
    dueDate: new Date('2024-12-12'),
    estimatedHours: 24,
    actualHours: 20,
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-12-10'),
  },
]

// Mock Rewards
export const mockRewards: Reward[] = [
  {
    id: 'r1',
    name: 'Gift Card Amazon $50',
    description: 'Tarjeta de regalo de Amazon por $50 USD',
    pointsCost: 500,
    category: 'gift_card',
    available: true,
  },
  {
    id: 'r2',
    name: 'Gift Card Uber Eats $25',
    description: 'Tarjeta de regalo de Uber Eats por $25 USD',
    pointsCost: 250,
    category: 'gift_card',
    available: true,
  },
  {
    id: 'r3',
    name: 'Dia libre extra',
    description: 'Un dia adicional de vacaciones pagadas',
    pointsCost: 1000,
    category: 'time_off',
    available: true,
  },
  {
    id: 'r4',
    name: 'Curso Udemy Premium',
    description: 'Acceso a cualquier curso premium de Udemy',
    pointsCost: 300,
    category: 'experience',
    available: true,
  },
  {
    id: 'r5',
    name: 'Bono $100',
    description: 'Bono de $100 USD en tu siguiente pago',
    pointsCost: 800,
    category: 'bonus',
    available: true,
  },
  {
    id: 'r6',
    name: 'Audifonos Sony WH-1000XM4',
    description: 'Audifonos inalambricos premium con cancelacion de ruido',
    pointsCost: 3000,
    category: 'merchandise',
    available: true,
  },
]

// Mock Activities
export const mockActivities: Activity[] = [
  {
    id: 'a1',
    userId: '3',
    userName: 'Juan Perez',
    action: 'created',
    entityType: 'lead',
    entityId: 'l1',
    entityName: 'Roberto Diaz',
    createdAt: new Date('2024-12-05T10:30:00'),
  },
  {
    id: 'a2',
    userId: '3',
    userName: 'Juan Perez',
    action: 'contacted',
    entityType: 'lead',
    entityId: 'l2',
    entityName: 'Sofia Herrera',
    createdAt: new Date('2024-12-05T09:15:00'),
  },
  {
    id: 'a3',
    userId: '4',
    userName: 'Ana Rodriguez',
    action: 'assigned',
    entityType: 'task',
    entityId: 't2',
    entityName: 'API de autenticacion',
    metadata: { assignedTo: 'Pedro Martinez' },
    createdAt: new Date('2024-12-05T08:00:00'),
  },
  {
    id: 'a4',
    userId: '5',
    userName: 'Pedro Martinez',
    action: 'completed',
    entityType: 'task',
    entityId: 't1',
    entityName: 'Diseño de base de datos',
    createdAt: new Date('2024-12-04T17:30:00'),
  },
  {
    id: 'a5',
    userId: '3',
    userName: 'Juan Perez',
    action: 'won',
    entityType: 'lead',
    entityId: 'l6',
    entityName: 'Isabella Mendez',
    metadata: { value: 55000 },
    createdAt: new Date('2024-11-30T14:00:00'),
  },
]

// Mock Point Events
export const mockPointEvents: PointEvent[] = [
  {
    id: 'pe1',
    userId: '3',
    type: 'sale_closed',
    points: 550,
    description: 'Venta cerrada: EduLearn LMS',
    referenceId: 'l6',
    createdAt: new Date('2024-11-30'),
  },
  {
    id: 'pe2',
    userId: '5',
    type: 'milestone_reached',
    points: 100,
    description: 'Milestone: Base de datos completada',
    referenceId: 't1',
    createdAt: new Date('2024-12-08'),
  },
  {
    id: 'pe3',
    userId: '4',
    type: 'sla_met',
    points: 50,
    description: 'SLA cumplido: HealthTech en tiempo',
    referenceId: 'p3',
    createdAt: new Date('2024-12-05'),
  },
]

// Helper functions
export function getLeadsByStatus(status: Lead['status']): Lead[] {
  return mockLeads.filter((lead) => lead.status === status)
}

export function getProjectsByStatus(status: Project['status']): Project[] {
  return mockProjects.filter((project) => project.status === status)
}

export function getTasksByProject(projectId: string): Task[] {
  return mockTasks.filter((task) => task.projectId === projectId)
}

export function getTasksByUser(userId: string): Task[] {
  return mockTasks.filter((task) => task.assignedTo === userId)
}

export function getUserById(userId: string): User | undefined {
  return mockUsers.find((user) => user.id === userId)
}

export function getLeadsByUser(userId: string): Lead[] {
  return mockLeads.filter((lead) => lead.assignedTo === userId)
}

export function getProjectsByPM(pmId: string): Project[] {
  return mockProjects.filter((project) => project.pmId === pmId)
}

export function getProjectsByDev(devId: string): Project[] {
  return mockProjects.filter((project) => project.teamIds.includes(devId))
}
